node:
  build: .
  ports:
   - "80:80"
   - "443:443"
   - "8080:8080"
  volumes:
   - .:/usr/src/app/
  links:
   - postgres
  environment:
    SLACK_OAUTH_TOKEN:
    DOCKER_HOST:
    IMESSAGE_LIBERATOR_PORT:

postgres:
  build: database/
  ports:
   - "5432:5432"
